dataset = "clotho"  # clotho | audiocaps
download_audiocaps = False  # used only in prepare script
metrics = "all"  # see aac_metrics.functional.evaluate
inference = True
save_inference_results = True
evaluation = True
baseline = False  # Inference on baseline model
quantization = False  # Inference on quantized model
pruning = False  # Inference on pruned model
kd = True  # Inference on saved kd model
kd_model = "best_student_model.pth"  # Path to kd model
